//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApplication1.ConverterServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConverterServiceReference.TempConService")]
    public interface TempConService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TempConService/c2f", ReplyAction="http://tempuri.org/TempConService/c2fResponse")]
        double c2f(double c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TempConService/c2f", ReplyAction="http://tempuri.org/TempConService/c2fResponse")]
        System.Threading.Tasks.Task<double> c2fAsync(double c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TempConService/f2c", ReplyAction="http://tempuri.org/TempConService/f2cResponse")]
        double f2c(double f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TempConService/f2c", ReplyAction="http://tempuri.org/TempConService/f2cResponse")]
        System.Threading.Tasks.Task<double> f2cAsync(double f);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TempConServiceChannel : MyWebApplication1.ConverterServiceReference.TempConService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TempConServiceClient : System.ServiceModel.ClientBase<MyWebApplication1.ConverterServiceReference.TempConService>, MyWebApplication1.ConverterServiceReference.TempConService {
        
        public TempConServiceClient() {
        }
        
        public TempConServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TempConServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TempConServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TempConServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double c2f(double c) {
            return base.Channel.c2f(c);
        }
        
        public System.Threading.Tasks.Task<double> c2fAsync(double c) {
            return base.Channel.c2fAsync(c);
        }
        
        public double f2c(double f) {
            return base.Channel.f2c(f);
        }
        
        public System.Threading.Tasks.Task<double> f2cAsync(double f) {
            return base.Channel.f2cAsync(f);
        }
    }
}
